### ISSUE TITLE
Plugin is now compatible with current Canvas

### ISSUE THREAD

**Issue by backuardo** [pmndrs/react-three-babel#9]
There seems to be some outdated documentation re: using the react-three-babel plugin with the react-three-fiber Canvas component. Since v8 react-three-fiber has used createRoot.

**Comment by CodyJasonBennett** [comment]
The plugin docs are indeed incorrect, but that tree-shaking is broken by the `extend(THREE)` call in `Canvas` despite the use of `createRoot`. I have #10 which resolves this limitation of the plugin.

**Comment by umar-ahmed** [comment]
This should be resolved now as #10 was merged.

I've published a new release on [NPM](https://www.npmjs.com/package/@react-three/babel) and [GitHub](https://github.com/pmndrs/react-three-babel/releases/tag/v1.0.1)
